
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black isort pytest
      - name: Lint (flake8)
        run: flake8 . || true
      - name: Style (black --check)
        run: black --check . || true
      - name: Imports (isort --check-only)
        run: isort --check-only . || true
      - name: Tests
        run: pytest -q
