name: Weekly FIRST Email

on:
  schedule:
    - cron: '0 14 * * 1'  # Every Monday at 14:00 UTC
  workflow_dispatch:

jobs:
  send-weekly-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weekly email script
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_TO: ${{ secrets.SMTP_TO }}
          FIRST_DATA: data/Food_Insecurity_Input_With_Actions.xlsx
          FIRST_SHEET: Food Insecurity Inputs
          EMAIL_SUBJECT: 'FIRST — Weekly Food Insecurity Summary'
          EMAIL_BODY: 'Please find attached the latest weekly summary.'
        run: |
          python scripts/weekly_email.py
