
name: Weekly Export to S3

on:
  schedule:
    - cron: '0 14 * * 1'  # Monday 14:00 UTC
  workflow_dispatch:

jobs:
  export-to-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt boto3 pandas matplotlib openpyxl
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Run export
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_PREFIX: ${{ secrets.AWS_S3_PREFIX }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          FIRST_DATA: data/Food_Insecurity_Input_With_Actions.xlsx
          FIRST_SHEET: Food Insecurity Inputs
        run: |
          python scripts/weekly_export_s3.py
